### ISSUE TITLE
Kick in game + cheat menu not loading is there assets to? I do not see them

### ISSUE THREAD

**Issue by Jimbob11111** [lgv-0/BoCheat-Unturned#20]
Hey there i have a issue @lgv-0  I think it's the cheat, I inject using my Mono injector called main.yo HIn , MainYo , for namespace class, method and im in the menu, i try join a server it says map issue etc, i tried joining then injecting whilst in game once i injected whilst connected to server it said "Server lost your connection" Please get back to me with the fix pls !! thanks < <

**Comment by Jimbob11111** [comment]
+ menu just doesn't load at all, either there is assets or I'm just a idiot 🗡️ :D

**Comment by Jimbob11111** [comment]
add my discord please Gintoki#9650

**Comment by Omega1031** [comment]
Yea a while back i also tried to figure out how to use/inject the cheat and never found a way. I don't think the regular sharp mono injector will work sadly.

**Comment by Jimbob11111** [comment]
Did you just say "Sharp mono injector? lmfao"

**Comment by Jimbob11111** [comment]
There's a reason why that wouldn't Work I need some other person to reply to this thread who actually knows what there doing.

**Comment by Omega1031** [comment]
> There's a reason why that wouldn't Work I need some other person to reply to this thread who actually knows what there doing.

I didn't know we had an elitist good luck getting help.

**Comment by lgv-0** [comment]
@Omega1031 You are correct, OOB the [**Sharp Mono Injector**](https://github.com/warbler/SharpMonoInjector) doesn't get as far as detecting the process properly.

@Jimbob11111 GitHub is not a place for this behavior, but nonetheless this sounds like a problem with your injector. The cheat will [allocate a console](https://github.com/lgv-0/BoCheat-Unturned/blob/master/HInj/HInj/IConsole.cs) when an injection is successful, otherwise you might need to peek around the Unity logging directories for any errors loading, usually it's a great hint.

I'm closing this topic.
