### ISSUE TITLE
visuals/aim dont work boss

### ISSUE THREAD

**Issue by Coopyy** [lgv-0/BoCheat-Unturned#4]
title, in a group or whatever didnt change anything. havent looked much into the source so i might be retarded l0l

**Comment by lgv-0** [comment]
Hey, thanks for the interest, but the issue is _very_ vague. I was able to get the current release compiled and working so I'm not sure what the issue is, but if I were to guess it's a dependency issue. This project has outside dependencies.

https://docs.microsoft.com/en-us/visualstudio/ide/managing-references-in-a-project?view=vs-2019

**Comment by Coopyy** [comment]
if it didnt have references added id imagine it wouldnt compile. a lot of drawing spam in my logs aswell 
[output_log.txt](https://github.com/lgv-0/BoCheat-Unturned/files/3800895/output_log.txt)
i deleted most of the logs as it was 47 mb, but you get the idea

**Comment by Coopyy** [comment]
oh it loads assets
nevermind
brainlet moment
