### ISSUE TITLE
Mono injector issues

### ISSUE THREAD

**Issue by DollarGangstaDollar** [lgv-0/BoCheat-Unturned#9]
The mono injector i'm using, which is SharpMonoInjector 2.2 has no processes when I click the drop down to pick a process.
![f165c36e2f26589cbc0bf5a841d35941](https://user-images.githubusercontent.com/36424103/71451182-91b43100-2725-11ea-9ea3-77d9a5b0f33d.png)

**Comment by lgv-0** [comment]
This GitHub page should be used only for the cheat itself. If you're having issues detecting processes, please direct it to the [appropriate pages](https://github.com/warbler/SharpMonoInjector). And this being the case, since theble project is open source, you should be a to find an explanation as to why by looking through the source code.
